fix: issue with constant orgTeams
  /home/runner/work/_actions/skymoore/required-approvals/main/dist/index.js:9004
  orgTeams = allOrgTeams;
  ^

TypeError: Assignment to constant variable.
  at main (/home/runner/work/_actions/skymoore/required-approvals/main/dist/index.js:9004:18)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)